# This is a basic workflow to help you get started with Actions

name: CI

env:
  landingName: "triangular"
  branchName: ${GITHUB_REF##*/}
  landingDir: "triangular"

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Prints current branch
        run: echo ${GITHUB_REF##*/}
        
      - name: Prints env variable
        run: echo ${{ env.landingName }}
  # another job
  branches:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      
      - name: Prints current branch and env.branch
        run: |
          echo ${GITHUB_REF##*/}
          echo ${{ env.branchName }}
  # job on pull request
  pullreq:
    runs-on: ubuntu-latest
    # if: github.head_ref == 'refs/heads/main'
    steps:
     - name: only on pull request
       if: ${{ github.event_name == 'pull_request' && github.event.action == 'unassigned' }}
       run:  |
        echo This event is a pull request that had an assignee removed.
        echo ${GITHUB_HEAD_REF##*/}
      
      
  
        
